# .basrc for jfreden

alias ls='ls --color'
alias ll='ls -al'
alias kload='kinit -ft ~/.kerberos/${USERNAME}.keytab ${USERNAME}@FNAL.GOV && klist'

export PATH=$PATH:~/bin:.
export KRB5_CONFIG=~/.kerebos/krb5.conf
