name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
      - cron: '0 0 * * *'

jobs:
  linux-config:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Run Linux config tests
      run: make -C fnal-asic-linux-config test


  macos-config:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Run MacOS tests
      run: make -C fnal-asic-macos-config test
